backend:
  name: git-gateway
  branch: main

media_folder: "images"

collections:
  - name: "readings"
    label: "Reading" 
    folder: "_posts/readings"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "string", default: "post" }
      - { label: "Categories", name: "categories", widget: "string", default: "readings" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }
      - { label: "Pages", name: "pages", widget: "string" }
      - { label: "Week", name: "week", widget: "string" }
      - { label: "Color", name: "color", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
 